# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20170602_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='status',
            field=models.IntegerField(choices=[(0, 'Open'), (1, 'Close'), (2, 'Canceled'), (3, 'Disqualified ')], default=0),
            preserve_default=False,
        ),
    ]
