# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('election', '0003_election_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='user.Group'),
            preserve_default=False,
        ),
    ]
