# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_election_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='description',
            field=models.TextField(default=1, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='election',
            name='name',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
